/* eslint-disable */
// Generated by Wrangler with runtime types omitted.
interface __BaseEnv_Env {
	SEC_FILINGS: R2Bucket;
	MAX_SITE_ORIGIN: "https://max-investment-record.max-zhangyuchen.chatgpt.site";
	IBKR_FLEX_QUERY_ID: "1628251";
	SEC_USER_AGENT: "max-investment-record/1.0 max.zhangyuchen@gmail.com";
	SEC_ANALYSIS_MODEL: "deepseek-v4-flash";
	SEC_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./index").SecAnalysisWorkflow['run']>[0]['payload']>;
	SEC_MEMORY_WORKFLOW: Workflow<Parameters<import("./index").SecMemoryWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MAX_SITE_ORIGIN" | "IBKR_FLEX_QUERY_ID" | "SEC_USER_AGENT" | "SEC_ANALYSIS_MODEL">> {}
}
