/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/sec-cron/wrangler.jsonc --include-runtime=false workers/sec-cron/worker-configuration.d.ts` (hash: 39e7b0ce9c00a7ef1602bc87e90637ab)
interface __BaseEnv_Env {
	MAX_SITE_ORIGIN: "https://investment-record.max-zhangyuchen.workers.dev";
	PORTFOLIO_TARGET_PLATFORM: "cloudflare";
	IBKR_FLEX_QUERY_ID: "1628251";
	PORTFOLIO_SITE: Fetcher /* investment-record */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MAX_SITE_ORIGIN" | "PORTFOLIO_TARGET_PLATFORM" | "IBKR_FLEX_QUERY_ID">> {}
}
