/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/sec-cron/wrangler.jsonc --include-runtime=false workers/sec-cron/worker-configuration.d.ts` (hash: f7f77349f6168167714167db7a7ac39d)
interface __BaseEnv_Env {
	IBKR_FLEX_QUERY_ID: "1628251";
	PORTFOLIO_SERVICE: Fetcher /* investment-record */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "IBKR_FLEX_QUERY_ID">> {}
}
