export type Language = "zh-CN" | "en";
export const languageKey = "max-investment-record:language";
export const parseLanguage = (value: unknown): Language => value === "en" ? "en" : "zh-CN";
const english: Record<string, string> = {
  "加仓": "Add", "减仓": "Reduce", "止损": "Stop loss", "目标": "Target", "自动保存中…": "Autosaving…", "已自动保存": "Autosaved", "计划已保存": "Plan saved", "计划保存失败。": "Could not save the plan.", "有新的更改待保存": "Unsaved changes", "计划数据暂时无法读取，请稍后再试。": "Plan unavailable. Please try again later.", "为什么持有它？什么事实支持这个判断？": "Why hold this asset? What evidence supports your thesis?", "规划点位": "Price levels", "把价格、动作和触发条件写在决策发生之前。": "Set prices, actions and triggers before making a decision.", "添加点位": "Add level", "点位": "Level", "动作": "Action", "目标价格": "Target price", "执行规模": "Trade size", "20 股 / 目标 8%": "20 shares / target 8%", "触发条件": "Trigger", "估值回落且基本面未变": "Lower valuation with unchanged fundamentals", "尚未设置点位。可以先保存持仓原因，再逐步补充。": "No price levels yet. Save your thesis first and add levels later.", "保存中…": "Saving…", "立即保存": "Save now",
  "顺风": "Tailwind", "逆风": "Headwind", "多空交织": "Mixed", "方向待确认": "Unclear", "0–5 个交易日": "0–5 trading days", "1–12 周": "1–12 weeks", "1–4 个季度": "1–4 quarters", "高置信": "High confidence", "中等置信": "Medium confidence", "低置信": "Low confidence", "利率": "Rates", "通胀": "Inflation", "增长": "Growth", "流动性": "Liquidity", "美元": "USD", "波动率": "Volatility", "图表暂时无法载入。": "Chart unavailable. ", "在 TradingView 查看": "View on TradingView", "图表由 TradingView 提供": "Chart by TradingView", "更新延迟": "Update delayed", "部分覆盖": "Partial coverage", "已更新": "Updated", "上海时间": "Shanghai time ", "事件窗口：过去 24 小时 / 未来 7 天": "Event window: last 24 hours / next 7 days", "今日宏观影响": "Today's macro impact", "已确认事实": "Confirmed facts", "传导路径": "Transmission", "组合含义": "Portfolio implications", "来源": "Source", "过去 24 小时没有纳入范围的高、中影响事件。": "No covered high or medium impact events in the last 24 hours.", "市场与利率走势": "Markets and rates", "美国大盘": "US equities", "美债期限 ETF": "Treasury ETFs", "未来七天经济事件": "Economic events in the next seven days", "高": "High", "中": "Medium", "美国 · 待发布": "US · Upcoming", "日程来源": "Calendar source", "来源与口径": "Sources & methodology", "事件事实来自美国官方发布。组合影响为基于当前持仓的传导判断，不是交易指令。TradingView 行情可能因交易所权限而延迟。": "Events are sourced from official US releases. Portfolio implications assess effects on current holdings and are not trade instructions. TradingView quotes may be delayed by exchange permissions.",
  "没有找到匹配的标的，请检查 ticker 或公司名称。": "No matches. Check the ticker or company name.", "搜索暂时不可用，请稍后重试。": "Search unavailable. Please try again later.", "计划暂时无法读取，请稍后重试。": "Plans unavailable. Please try again later.",
  "设置": "Settings", "外观与语言": "Appearance & language", "按你的习惯调整显示方式。": "Choose how your workspace looks.", "主题": "Theme", "日间模式": "Light", "夜间模式": "Dark", "跟随系统": "System", "语言": "Language", "研究正文与自行填写的内容保留原文。": "Research and your own notes stay in their original language.", "更改即时生效，并保存在此浏览器。": "Changes apply instantly and are saved in this browser.",
  "投资记录": "Investment record", "公司业务分析": "Company analysis", "宏观分析": "Macro analysis", "主导航": "Main navigation", "展开主导航": "Expand navigation", "当前净值": "Net asset value", "累计盈亏": "Total P&L", "组合摘要": "Portfolio summary", "持仓净市值": "Net position value", "现金": "Cash", "杠杆率": "Leverage", "净入金": "Net deposits", "持仓摘要": "Holdings summary", "正股": "Stocks", "期权": "Options", "剔除期权浮盈亏": "NAV excluding option P&L", "即将到来的事件": "Upcoming events", "北京": "Beijing ", "前四大持仓": "Top four holdings", "其他": "Other", "其他持仓与空头调整": "Other holdings and short adjustments", "现金与对冲": "Cash & hedges", "已归类板块": "Classified sectors", "板块占比图例": "Sector allocation legend", "个股": "Holdings", "板块": "Sectors",
  "标的": "Symbol", "现价": "Price", "日涨跌": "Day change", "净市值": "Net value", "净权重": "Net weight", "摊薄成本": "Adjusted cost", "持仓成本": "Cost basis", "未实现盈亏": "Unrealized P&L", "年内已实现": "YTD realized", "年内净盈亏": "YTD net P&L", "按 Ticker 分类的持仓": "Holdings by ticker", "投资账本": "Investment ledger", "，查看持仓详情": ", view holding details", "读取中": "Loading", "张": "contracts", "当前快照没有持仓。": "No holdings in the current snapshot.", "首次交易": "First trade", "最近交易": "Last trade", "正股成交": "Stock trades", "期权成交": "Option trades", "累计已实现盈亏": "Total realized P&L", "按 Ticker 分类的历史持仓": "Historical holdings by ticker", "历史投资账本": "Historical investment ledger", "笔": "trades", "Flex 成交记录中还没有已清仓标的。": "No closed positions in the Flex trade history.", "仓位分析": "Allocation analysis", "仓位构成与热力图": "Allocation and heatmap", "收起": "Collapse", "展开": "Expand", "仓位构成": "Allocation", "账本持仓范围": "Ledger view", "当前持仓": "Current holdings", "历史持仓": "Past holdings", "持仓计划": "Holding plans",
  "持仓主题热力图": "Holdings heatmap", "总敞口": "Gross exposure", "总敞口计算口径": "Gross exposure calculation", "热力图内正股市值 ÷ 当前净值；期权负债不进入热力图。": "Stock market value in the heatmap divided by NAV. Option liabilities are excluded.", "热力图显示方式": "Heatmap display", "日涨跌幅": "Day change", "切换日涨跌幅与公司 Logo": "Toggle day change and company logos", "公司 Logo": "Company logos", "市值": "Market value", "组合权重": "Portfolio weight", "重试": "Retry", "持仓原因": "Investment thesis", "添加持仓计划": "Add holding plan", "输入美股 ticker 或公司名称，选择后进入独立详情页。": "Search a US ticker or company to open its detail page.", "搜索 ticker 或公司": "Search ticker or company", "正在搜索": "Searching", "搜索 ticker 或公司名称": "Search ticker or company name", "搜索结果": "Search results", "股票": "Stock", "证券目录更新于": "Directory updated ",
  "超买": "Overbought", "超卖": "Oversold", "偏强": "Strong", "中性": "Neutral", "未持有 · 预先规划": "Not held · Planning", "股价": "Share price", "RSI 14 · 日线": "RSI 14 · Daily", "行情读取中": "Loading quote", "行情暂不可用": "Quote unavailable", "详情章节": "Detail sections", "持仓构成": "Position breakdown", "SEC 文件": "SEC filings", "类型": "Type", "资产 / 合约": "Asset / Contract", "数量": "Quantity", "平均成本": "Average cost", "实际成本": "Adjusted cost", "权重": "Weight", "暂无持仓数据": "No holding data", "这份计划不会写入 IBKR 账本；建立持仓后，快照数据会自动出现在这里。": "This plan does not modify the IBKR ledger. Holdings will appear here after a position is opened.", "正在读取计划": "Loading plan", "跳到主要内容": "Skip to main content"
};
export function translate(text: string, language: Language): string {
  if (language === "zh-CN") return text;
  const trimmed = text.trim();
  const translated = english[trimmed];
  return translated === undefined ? text : text.replace(trimmed, translated);
}
