/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/pipeline/wrangler.jsonc --include-runtime=false workers/pipeline/worker-configuration.d.ts` (hash: 29a619391da298ceffdc0532e8af38d6)
interface __BaseEnv_Env {
	SEC_FILINGS: R2Bucket;
	ANALYSIS_READ_RATE_LIMIT: RateLimit;
	SEC_USER_AGENT: "earning-report-analysis/1.0 max.zhangyuchen@gmail.com";
	SEC_ANALYSIS_MODEL: "glm-5.3-flash";
	SEC_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./src/index").SecAnalysisWorkflow['run']>[0]['payload']>;
	SEC_MEMORY_WORKFLOW: Workflow<Parameters<import("./src/index").SecMemoryWorkflow['run']>[0]['payload']>;
	COMPANY_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./src/index").CompanyAnalysisWorkflow['run']>[0]['payload']>;
	COMPANY_ANALYSIS_BACKFILL_WORKFLOW: Workflow<Parameters<import("./src/index").CompanyAnalysisBackfillWorkflow['run']>[0]['payload']>;
	DB?: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		SEC_FILINGS: R2Bucket;
		ANALYSIS_READ_RATE_LIMIT: RateLimit;
		SEC_USER_AGENT: "earning-report-analysis/1.0 max.zhangyuchen@gmail.com";
		SEC_ANALYSIS_MODEL: "glm-5.3-flash";
		SEC_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./src/index").SecAnalysisWorkflow['run']>[0]['payload']>;
		SEC_MEMORY_WORKFLOW: Workflow<Parameters<import("./src/index").SecMemoryWorkflow['run']>[0]['payload']>;
		COMPANY_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./src/index").CompanyAnalysisWorkflow['run']>[0]['payload']>;
		COMPANY_ANALYSIS_BACKFILL_WORKFLOW: Workflow<Parameters<import("./src/index").CompanyAnalysisBackfillWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SEC_USER_AGENT" | "SEC_ANALYSIS_MODEL">> {}
}
